# image: node:14.18.1

# cache:
#   paths:
#     - node_modules/
#   key: "$CI_BUILD_REPO"

# before_script:
#   - npm i -g firebase-tools
#   - npm i

# stages:
#   - deploy-dev
#   - deploy-prod

# deploy-dev:
#   stage: deploy-dev
#   only:
#     - development
#   script:
#     - echo $DEV_WEBAPP_CONFIGS > src/config.json
#     - echo $DEV_WEBAPP_FIREBASE_RC > .firebaserc
#     - npm run build
#     - echo "Déploiement vers firebase Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID"
#     - npm run deploy-ci

# deploy-prod:
#   stage: deploy-prod
#   only:
#     - production
#   script:
#     - echo $PROD_WEBAPP_CONFIGS > src/config.json
#     - echo $PROD_WEBAPP_FIREBASE_RC > .firebaserc
#     - npm run build
#     - echo "Déploiement vers firebase Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID"
#     - npm run deploy-ci
